name: crud_with_supabase
description: "Create Flutter CRUD Board with Supabase (feat. 2nd IGNIGHT, CodeFactory)"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.3.0
  flutter_riverpod: ^2.6.0
  cupertino_icons: ^1.0.8
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.3
  supabase_flutter: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_lint: ^2.3.13
  custom_lint: ^0.6.8

flutter:
  uses-material-design: true
